pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('token-dockerhub')
        GITHUB_CREDENTIALS = credentials('github-token')
        REPO = 'arimateiajuniorunifor/controle-ingest-o-h2O'
        DOCKERHUB_REPO = 'arimateiajunior/controle-h2o'
        TAG = "backend-v${env.BUILD_NUMBER}"
        VENV_PATH = '/var/lib/jenkins/workspace/Pipeline - H2O/backend/h2o'
        PROJECT_PATH = '/var/lib/jenkins/workspace/Pipeline - H2O/backend'
        RECIPIENTS = 'arimateiajunior.tic@gmail.com'
        TELEGRAM_CHAT_ID = '231399891' // Verifique se este Chat ID está correto
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', credentialsId: env.GITHUB_CREDENTIALS, url: "https://github.com/${env.REPO}.git"
            }
        }

        stage('Build Docker Images') {
            steps {
                sh 'docker-compose build'
            }
        }

        stage('Verify Docker Images') {
            steps {
                sh 'docker images'
            }
        }

        stage('Tag and Push to Docker Hub') {
            steps {
                script {
                    def service = 'pipeline-h2o_backend'
                    def imageName = "${service}:latest"
                    def dockerHubTag = "${env.DOCKERHUB_REPO}:${env.TAG}"
                    
                    sh "docker inspect --type=image ${imageName} || exit 1"
                    sh "echo ${DOCKERHUB_CREDENTIALS_PSW} | docker login -u ${DOCKERHUB_CREDENTIALS_USR} --password-stdin"
                    
                    sh "docker tag ${imageName} ${dockerHubTag}"
                    sh "docker push ${dockerHubTag}"
                }
            }
        }

        stage('Test Backend') {
            steps {
                script {
                    sh """
                    . '${VENV_PATH}/bin/activate'
                    pip install -r '${PROJECT_PATH}/requirements.txt'
                    pytest '${PROJECT_PATH}/tests'
                    """
                }
            }
        }

        stage('Deploy to Production') {
            steps {
                sh 'docker-compose up -d'
            }
        }

        stage('Send Notifications') {
            steps {
                // Envie e-mail
                emailext (
                    subject: "Sucesso: Job ${env.JOB_NAME} [${env.BUILD_NUMBER}]",
                    body: "O pipeline foi executado com sucesso.\nVer detalhes no Jenkins: ${env.BUILD_URL}",
                    to: "${env.RECIPIENTS}"
                )

                // Envie mensagem pelo Telegram
                telegramSend(
                    chatId: "${env.TELEGRAM_CHAT_ID}",
                    text: "Pipeline concluído com sucesso! Job: ${env.JOB_NAME} [${env.BUILD_NUMBER}]. Detalhes: ${env.BUILD_URL}"
                )
            }
        }
    }

    post {
        success {
            echo 'Pipeline executado com sucesso!'
        }
        failure {
            echo 'Pipeline falhou.'
        }
    }
}
